### ISSUE TITLE
When our "things" are labeled with uppercase and lowercase letters, the command interpreter fails to find it

### ISSUE THREAD

**Issue by andrenatal** [mozilla/smarthome#11]
When we have an item written with both lower and uppercase letters, the regex splits the array in every uppercase occurrence.

For example, for the word: "WeMo Switch", the array will be: [We,Mo,,Switch]
But if the word has only lowercases "wemo switch", it splits correctly, and the array will be [ wemo, switch]

**Comment by andrenatal** [comment]
This hack #10 fixed the issue in English, but it needs more development and the problem is larger than just that as @kdavis-mozilla mentioned [here](https://github.com/mozilla/smarthome/pull/10#issuecomment-202310277)

**Comment by tilmankamp** [comment]
Merged fix into vaani.
