### ISSUE TITLE
 Items have incorrect labels or items are used incorrectly.

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/smarthome#14]
If one adds a SONOS player and calls it "music player"

![Things](https://irccloud.mozilla.com/file/Q8eYPX1n/Items.jpg)

with a channel "Control"

![Thing](https://irccloud.mozilla.com/file/lwpdcDKE/Item.jpg)
one finds the interpreter does not know about the "music player".

For example here is evidence form the OSGI command line

```
osgi> smarthome interpret play music player
There is no object named like that.
```

However, one does find an Item named "Control"

```
osgi> smarthome interpret play Control
Ok.
```

which causes the SONOS player to play.

So, it seems as if the interpreter is using a channel as an item.

PS: Peeking a bit at the code I found that the "music player" does appear as an item but the item is a group and this item-group does not accept the play/pause command type.

**Comment by tilmankamp** [comment]
I'll work on this...

**Comment by tilmankamp** [comment]
Merged fix into vaani.
