### ISSUE TITLE
OS X TTSService implementation should be moved to an extension

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/smarthome#52]
The new `OS X` `TTSService` implementation should be moved to

`extensions/voice/org.eclipse.smarthome.voice.mactts`

where the old implementation currently lives and the bundle 

`extensions/voice/org.eclipse.smarthome.voice.mactts`

should be re-enabled in `.travis.yml`

**Comment by tilmankamp** [comment]
Just started working on this. It is a part (of the problem) of the current rebasing effort.
